### ISSUE TITLE
DogScepter reading out bounds during loading of Sprite Chunk

### ISSUE THREAD

**Issue by Miepee** [colinator27/DogScepter#40]
Several games create the following exception:
```
System.IO.IOException: Reading out of bounds
   at DogScepterLib.Core.Util.BufferBinaryReader.ReadInt32() in C:\Users\narr\gitrepos\dog-scepter\DogScepterLib\Core\Util\BufferBinaryReader.cs:line 108
   at DogScepterLib.Core.Models.GMSprite.Deserialize(GMDataReader reader) in C:\Users\narr\gitrepos\dog-scepter\DogScepterLib\Core\Models\GMSprite.cs:line 208
   at DogScepterLib.Core.GMDataReader.ReadPointerObjectUnique[T](Int32 ptr, Boolean returnAfter) in C:\Users\narr\gitrepos\dog-scepter\DogScepterLib\Core\GMDataReader.cs:line 181
   at DogScepterLib.Core.GMPointerList`1.DoReadPointerObjectUnique(GMDataReader reader, Boolean notLast) in C:\Users\narr\gitrepos\dog-scepter\DogScepterLib\Core\GMLists.cs:line 167
   at DogScepterLib.Core.GMPointerList`1.Deserialize(GMDataReader reader, ListDeserialize before, ListDeserialize after, ListDeserializeElement elemReader) in C:\Users\narr\gitrepos\dog-scepter\DogScepterLib\Core\GMLists.cs:line
191
   at DogScepterLib.Core.GMPointerList`1.Deserialize(GMDataReader reader) in C:\Users\narr\gitrepos\dog-scepter\DogScepterLib\Core\GMLists.cs:line 199
   at DogScepterLib.Core.Chunks.GMChunkSPRT.Deserialize(GMDataReader reader) in C:\Users\narr\gitrepos\dog-scepter\DogScepterLib\Core\Chunks\GMChunkSPRT.cs:line 27
   at DogScepterLib.Core.GMChunkFORM.Deserialize(GMDataReader reader) in C:\Users\narr\gitrepos\dog-scepter\DogScepterLib\Core\GMChunk.cs:line 170
   at DogScepterLib.Core.GMDataReader.Deserialize(Boolean clearData) in C:\Users\narr\gitrepos\dog-scepter\DogScepterLib\Core\GMDataReader.cs:line 58
   at DogScepterCLI.ConsoleExtensions.LoadDataFile(IConsole console, String file, Boolean verbose) in C:\Users\narr\gitrepos\dog-scepter\DogScepterCLI\ConsoleExtensions.cs:line 127
 ```
 
 Games in question are:
 [down the road](https://gm48.net/game/1049), [Chromaticity](https://gm48.net/game/1173), [galactic graffit](https://gm48.net/game/1175), [haunted home not alone](https://gm48.net/game/1279), [desolation](https://gm48.net/game/1282), [detective](https://gm48.net/game/1354), [tower-guy](https://gm48.net/game/1411), [a picture a memory](https://gm48.net/game/1493), [one musician per pond](https://gm48.net/game/1606), [async](https://gm48.net/game/1617), [dr rekoil and the last judgement](https://gm48.net/game/1630), [on the flip side](https://gm48.net/game/1644), [the cardboard box](https://gm48.net/game/1655), [kitty citty](https://gm48.net/game/1674), [the bling bling pumpking king ahrvest pumpkin festival](https://gm48.net/game/1758), [blackheart no](https://gm48.net/game/1779), [island](https://gm48.net/game/1938), [radio you f o](https://gm48.net/game/1974), [dodgeball duke](https://gm48.net/game/2)

**Comment by Miepee** [comment]
This may be a duplicate of #17 actually.
